CREATE TABLE SELLERINFO(
SELLERID NVARCHAR(50) NOT NULL,
NAME VARCHAR(50) NOT NULL,
AGE NVARCHAR(50) NOT NULL,
GENDER VARCHAR(50) NOT NULL,
PHONENUMBER NVARCHAR(50) NOT NULL,
CITY VARCHAR(50) NOT NULL
);
